# source: https://developers.google.com/fit/rest/v1/reference/activity-types
activity_types = [
  { name: 'Aerobics', googleID: 9 },
  { name: 'Badminton', googleID: 10 },
  { name: 'Baseball', googleID: 11 },
  { name: 'Basketball', googleID: 12 },
  { name: 'Biathlon', googleID: 13 },
  { name: 'Biking', googleID: 1 },
  { name: 'Handbiking', googleID: 14 },
  { name: 'Mountain biking', googleID: 15 },
  { name: 'Road biking', googleID: 16 },
  { name: 'Spinning', googleID: 17 },
  { name: 'Stationary biking', googleID: 18 },
  { name: 'Utility biking', googleID: 19 },
  { name: 'Boxing', googleID: 20 },
  { name: 'Calisthenics', googleID: 21 },
  { name: 'Circuit training', googleID: 22 },
  { name: 'Cricket', googleID: 23 },
  { name: 'Curling', googleID: 106 },
  { name: 'Dancing', googleID: 24 },
  { name: 'Diving', googleID: 102 },
  { name: 'Elliptical', googleID: 25 },
  { name: 'Ergometer', googleID: 103 },
  { name: 'Fencing', googleID: 26 },
  { name: 'Football (American)', googleID: 27 },
  { name: 'Football (Australian)', googleID: 28 },
  { name: 'Football (Soccer)', googleID: 29 },
  { name: 'Frisbee', googleID: 30 },
  { name: 'Gardening', googleID: 31 },
  { name: 'Golf', googleID: 32 },
  { name: 'Gymnastics', googleID: 33 },
  { name: 'Handball', googleID: 34 },
  { name: 'Hiking', googleID: 35 },
  { name: 'Hockey', googleID: 36 },
  { name: 'Horseback riding', googleID: 37 },
  { name: 'Housework', googleID: 38 },
  { name: 'Ice skating', googleID: 104 },
  { name: 'In vehicle', googleID: 0 },
  { name: 'Jumping rope', googleID: 39 },
  { name: 'Kayaking', googleID: 40 },
  { name: 'Kettlebell training', googleID: 41 },
  { name: 'Kickboxing', googleID: 42 },
  { name: 'Kitesurfing', googleID: 43 },
  { name: 'Martial arts', googleID: 44 },
  { name: 'Meditation', googleID: 45 },
  { name: 'Mixed martial arts', googleID: 46 },
  { name: 'On foot', googleID: 2 },
  { name: 'Other (unclassified fitness activity)', googleID: 108 },
  { name: 'P90X exercises', googleID: 47 },
  { name: 'Paragliding', googleID: 48 },
  { name: 'Pilates', googleID: 49 },
  { name: 'Polo', googleID: 50 },
  { name: 'Racquetball', googleID: 51 },
  { name: 'Rock climbing', googleID: 52 },
  { name: 'Rowing', googleID: 53 },
  { name: 'Rowing machine', googleID: 54 },
  { name: 'Rugby', googleID: 55 },
  { name: 'Running', googleID: 8 },
  { name: 'Jogging', googleID: 56 },
  { name: 'Running on sand', googleID: 57 },
  { name: 'Running (treadmill)', googleID: 58 },
  { name: 'Sailing', googleID: 59 },
  { name: 'Scuba diving', googleID: 60 },
  { name: 'Skateboarding', googleID: 61 },
  { name: 'Skating', googleID: 62 },
  { name: 'Cross skating', googleID: 63 },
  { name: 'Indoor skating', googleID: 105 },
  { name: 'Inline skating (rollerblading)', googleID: 64 },
  { name: 'Skiing', googleID: 65 },
  { name: 'Back-country skiing', googleID: 66 },
  { name: 'Cross-country skiing', googleID: 67 },
  { name: 'Downhill skiing', googleID: 68 },
  { name: 'Kite skiing', googleID: 69 },
  { name: 'Roller skiing', googleID: 70 },
  { name: 'Sledding', googleID: 71 },
  { name: 'Sleeping', googleID: 72 },
  { name: 'Light sleep', googleID: 109 },
  { name: 'Deep sleep', googleID: 110 },
  { name: 'REM sleep', googleID: 111 },
  { name: 'Awake (during sleep cycle)', googleID: 112 },
  { name: 'Snowboarding', googleID: 73 },
  { name: 'Snowmobile', googleID: 74 },
  { name: 'Snowshoeing', googleID: 75 },
  { name: 'Squash', googleID: 76 },
  { name: 'Stair climbing', googleID: 77 },
  { name: 'Stair-climbing machine', googleID: 78 },
  { name: 'Stand-up paddleboarding', googleID: 79 },
  { name: 'Still (not moving)', googleID: 3 },
  { name: 'Strength training', googleID: 80 },
  { name: 'Surfing', googleID: 81 },
  { name: 'Swimming', googleID: 82 },
  { name: 'Swimming (open water)', googleID: 84 },
  { name: 'Swimming (swimming pool)', googleID: 83 },
  { name: 'Table tennis (ping pong)', googleID: 85 },
  { name: 'Team sports', googleID: 86 },
  { name: 'Tennis', googleID: 87 },
  { name: 'Tilting (sudden device gravity change)', googleID: 5 },
  { name: 'Treadmill (walking or running)', googleID: 88 },
  { name: 'Unknown (unable to detect activity)', googleID: 4 },
  { name: 'Volleyball', googleID: 89 },
  { name: 'Volleyball (beach)', googleID: 90 },
  { name: 'Volleyball (indoor)', googleID: 91 },
  { name: 'Wakeboarding', googleID: 92 },
  { name: 'Walking', googleID: 7 },
  { name: 'Walking (fitness)', googleID: 93 },
  { name: 'Nording walking', googleID: 94 },
  { name: 'Walking (treadmill)', googleID: 95 },
  { name: 'Waterpolo', googleID: 96 },
  { name: 'Weightlifting', googleID: 97 },
  { name: 'Wheelchair', googleID: 98 },
  { name: 'Windsurfing', googleID: 99 },
  { name: 'Yoga', googleID: 100 },
  { name: 'Zumba', googleID: 101 }
]

activity_types.each do |activity_params|
  ActivityType.create(activity_params)
end
