# source: https://developers.google.com/fit/rest/v1/reference/activity-types
activity_types = [
  { name: 'Aerobics', google_id: 9 },
  { name: 'Badminton', google_id: 10 },
  { name: 'Baseball', google_id: 11 },
  { name: 'Basketball', google_id: 12 },
  { name: 'Biathlon', google_id: 13 },
  { name: 'Biking', google_id: 1 },
  { name: 'Handbiking', google_id: 14 },
  { name: 'Mountain biking', google_id: 15 },
  { name: 'Road biking', google_id: 16 },
  { name: 'Spinning', google_id: 17 },
  { name: 'Stationary biking', google_id: 18 },
  { name: 'Utility biking', google_id: 19 },
  { name: 'Boxing', google_id: 20 },
  { name: 'Calisthenics', google_id: 21 },
  { name: 'Circuit training', google_id: 22 },
  { name: 'Cricket', google_id: 23 },
  { name: 'Curling', google_id: 106 },
  { name: 'Dancing', google_id: 24 },
  { name: 'Diving', google_id: 102 },
  { name: 'Elliptical', google_id: 25 },
  { name: 'Ergometer', google_id: 103 },
  { name: 'Fencing', google_id: 26 },
  { name: 'Football (American)', google_id: 27 },
  { name: 'Football (Australian)', google_id: 28 },
  { name: 'Football (Soccer)', google_id: 29 },
  { name: 'Frisbee', google_id: 30 },
  { name: 'Gardening', google_id: 31 },
  { name: 'Golf', google_id: 32 },
  { name: 'Gymnastics', google_id: 33 },
  { name: 'Handball', google_id: 34 },
  { name: 'Hiking', google_id: 35 },
  { name: 'Hockey', google_id: 36 },
  { name: 'Horseback riding', google_id: 37 },
  { name: 'Housework', google_id: 38 },
  { name: 'Ice skating', google_id: 104 },
  { name: 'In vehicle', google_id: 0 },
  { name: 'Jumping rope', google_id: 39 },
  { name: 'Kayaking', google_id: 40 },
  { name: 'Kettlebell training', google_id: 41 },
  { name: 'Kickboxing', google_id: 42 },
  { name: 'Kitesurfing', google_id: 43 },
  { name: 'Martial arts', google_id: 44 },
  { name: 'Meditation', google_id: 45 },
  { name: 'Mixed martial arts', google_id: 46 },
  { name: 'On foot', google_id: 2 },
  { name: 'Other (unclassified fitness activity)', google_id: 108 },
  { name: 'P90X exercises', google_id: 47 },
  { name: 'Paragliding', google_id: 48 },
  { name: 'Pilates', google_id: 49 },
  { name: 'Polo', google_id: 50 },
  { name: 'Racquetball', google_id: 51 },
  { name: 'Rock climbing', google_id: 52 },
  { name: 'Rowing', google_id: 53 },
  { name: 'Rowing machine', google_id: 54 },
  { name: 'Rugby', google_id: 55 },
  { name: 'Running', google_id: 8 },
  { name: 'Jogging', google_id: 56 },
  { name: 'Running on sand', google_id: 57 },
  { name: 'Running (treadmill)', google_id: 58 },
  { name: 'Sailing', google_id: 59 },
  { name: 'Scuba diving', google_id: 60 },
  { name: 'Skateboarding', google_id: 61 },
  { name: 'Skating', google_id: 62 },
  { name: 'Cross skating', google_id: 63 },
  { name: 'Indoor skating', google_id: 105 },
  { name: 'Inline skating (rollerblading)', google_id: 64 },
  { name: 'Skiing', google_id: 65 },
  { name: 'Back-country skiing', google_id: 66 },
  { name: 'Cross-country skiing', google_id: 67 },
  { name: 'Downhill skiing', google_id: 68 },
  { name: 'Kite skiing', google_id: 69 },
  { name: 'Roller skiing', google_id: 70 },
  { name: 'Sledding', google_id: 71 },
  { name: 'Sleeping', google_id: 72 },
  { name: 'Light sleep', google_id: 109 },
  { name: 'Deep sleep', google_id: 110 },
  { name: 'REM sleep', google_id: 111 },
  { name: 'Awake (during sleep cycle)', google_id: 112 },
  { name: 'Snowboarding', google_id: 73 },
  { name: 'Snowmobile', google_id: 74 },
  { name: 'Snowshoeing', google_id: 75 },
  { name: 'Squash', google_id: 76 },
  { name: 'Stair climbing', google_id: 77 },
  { name: 'Stair-climbing machine', google_id: 78 },
  { name: 'Stand-up paddleboarding', google_id: 79 },
  { name: 'Still (not moving)', google_id: 3 },
  { name: 'Strength training', google_id: 80 },
  { name: 'Surfing', google_id: 81 },
  { name: 'Swimming', google_id: 82 },
  { name: 'Swimming (open water)', google_id: 84 },
  { name: 'Swimming (swimming pool)', google_id: 83 },
  { name: 'Table tennis (ping pong)', google_id: 85 },
  { name: 'Team sports', google_id: 86 },
  { name: 'Tennis', google_id: 87 },
  { name: 'Tilting (sudden device gravity change)', google_id: 5 },
  { name: 'Treadmill (walking or running)', google_id: 88 },
  { name: 'Unknown (unable to detect activity)', google_id: 4 },
  { name: 'Volleyball', google_id: 89 },
  { name: 'Volleyball (beach)', google_id: 90 },
  { name: 'Volleyball (indoor)', google_id: 91 },
  { name: 'Wakeboarding', google_id: 92 },
  { name: 'Walking', google_id: 7 },
  { name: 'Walking (fitness)', google_id: 93 },
  { name: 'Nording walking', google_id: 94 },
  { name: 'Walking (treadmill)', google_id: 95 },
  { name: 'Waterpolo', google_id: 96 },
  { name: 'Weightlifting', google_id: 97 },
  { name: 'Wheelchair', google_id: 98 },
  { name: 'Windsurfing', google_id: 99 },
  { name: 'Yoga', google_id: 100 },
  { name: 'Zumba', google_id: 101 }
]

activity_types.each do |activity_params|
  ActivityType.create(activity_params)
end
